// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1_Ap1_RandyFabian.DAL;

#nullable disable

namespace Parcial1_Ap1_RandyFabian.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240212224829_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");
#pragma warning restore 612, 618
        }
    }
}
